name: Update Last Stargazer Badge

on:
  schedule:
    - cron: "0 * * * *" # Runs hourly
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-last-stargazer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch repository stargazers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}/stargazers \
          | jq -r '.[-1].login' > last_stargazer.txt

      - name: Update README with Badge
        run: |
          LAST_STARGAZER=$(cat last_stargazer.txt)
          BADGE_URL="https://img.shields.io/badge/%2ALAST%20STARGAZER%2A-${LAST_STARGAZER}-brightgreen?style=flat-square"
          sed -i.bak -E "s|!\[LAST STARGAZER\]\(.*\)|![LAST STARGAZER]($BADGE_URL)|" README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Last Stargazer badge"
          git push
